### ISSUE TITLE
Conversion from hex 200b to ASCII appears broken

### ISSUE THREAD

**Issue by zedgama3** [npp-plugins/converter#14]
# Steps to reproduce:
1. Open the conversion panel using *Plugins -> Converter -> Conversion Panel*
2. Enter a hexadecimal value of 200b
3. Click copy or insert for ASCII

# Expected result
That a ZERO LENGTH SPACE would be copied into the clipboard when *Copy* was clicked or inserted into the document when *Insert* was clicked.

# Actual result
Nothing.

The clipboard maintains previous contents and no new characters are added to the document.

**Comment by user21760** [comment]
The character ZLSP is not included in ASCII.
The panel works for Unicode codepoints from 00 to FF, which includes all the ASCII characters with the same codepoints (from 00 to 7F).
A codepoint with hexadecimal value 200B would mean 2 characters in ASCII : space (hex 20) followed by [VT] (hex 0B: vertical tabulation).

You would need a feature for hex to unicode conversion, like the one requested in this issue:  #7

**Comment by zedgama3** [comment]
Good catch.  I should have looked more closely.  Thank you for your response.
