### ISSUE TITLE
Converting "NUL" from ASCII to Hex results in "20" (space) instead of "00" 

### ISSUE THREAD

**Issue by levimatheri** [npp-plugins/converter#5]
This issue has been raised in the notepad-plus-plus repository [here](https://github.com/notepad-plus-plus/notepad-plus-plus/issues/4658). It looks like Scintilla returns the highlighted NUL text as a space. See [here](https://github.com/npp-plugins/converter/blob/fedffd71624ba64e96d34f3c6fea6f6b6861c1a4/source/PluginDefinition.cpp#L192-L209)

**Comment by tzdravev** [comment]
It seems like many users have seen that bug since Jul 12 2018 but it is yet open.

**Comment by Wufus** [comment]
To update "Npp Converter" to version 4.3 with this fix, you need to update Notepad ++ to version 8+.
